### ISSUE TITLE
Hash module

### ISSUE THREAD

**Issue by onesandzeros415** [jellever/Yara.NET#1]
Hello,

When running a scan with a rule that makes use of hash like : 

and not hash.md5(0,filesize) == "20cdf36e37b4fd0144afe1aaa8537f34"

Yara.NET dll gives the following error : Yara failed to scan given memory.\nYara Error: 34.

Am I doing something incorrect when making use of the hash module in my Yara rules?

**Comment by onesandzeros415** [comment]
Any update on this?

**Comment by jellever** [comment]
Sorry for the late reply! I just had a look at it. By default, the hash module is not compiled in the project. You can add the "HASH" preprocessor definition to the libyara project in the solution and this should fix your issue. 
![schermafdruk 2016-07-26 22 24 56](https://cloud.githubusercontent.com/assets/3390439/17154098/d93a9c44-537f-11e6-9624-8260dd4e9920.png)

**Comment by jellever** [comment]
My test rule:

import "hash"

rule MyHashYaraRule
{
    strings:
        $a = "test"
    condition:
        $a and not hash.md5(0,filesize) == "20cdf36e37b4fd0144afe1aaa8537f34"
}
